---
services:
  wwwallet-issuer-poc:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - "./config.yml:/app/config.yml"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
      start_interval: 5s

  k6:
    image: grafana/k6
    container_name: k6
    profiles:
      - k6
    volumes:
      - ./scripts:/scripts
    network_mode: host
    command: run /scripts/loadtest.oid4vci.k6.js
    depends_on:
      wwwallet-issuer-poc:
        condition: service_healthy
        restart: true
