---
issuer_url: "http://localhost:5000"
wallet_url: "http://localhost:3000"
issuer_display:
  - name: wwWallet Issuer
    locale: en-US
    logo:
      uri: https://demo-issuer.wwwallet.org/images/logo.png
clients:
  - id: CLIENT123
    secret: 321TNEILC
    scopes:
      - client:scope
      - ehic
      - diploma
      - pid:jpt_dc
      - pid:mso_mdoc
      - pid:sd_jwt_dc
      - pid:sd_jwt_dc:arf_1_5
      - pid:sd_jwt_vc:arf_1_5
      - pid:sd_jwt_vc
      - por:sd_jwt_vc
    redirect_uris:
      - http://localhost:3000
secret: "12345678901234567890123456789012" # 32 characters long secret
token_encryption: A128CBC-HS256 # see https://github.com/panva/jose/issues/210#jwe-enc
issuer_client:
  scopes:
    - ehic
    - diploma
    - pid:jpt_dc
    - pid:mso_mdoc
    - pid:sd_jwt_dc
    - pid:sd_jwt_dc:arf_1_5
    - pid:sd_jwt_vc:arf_1_5
    - pid:sd_jwt_vc
    - por:sd_jwt_vc
supported_credential_configuration_paths:
  - ./credential_configurations/pid:jpt_dc.json
  - ./credential_configurations/pid:sd_jwt_dc.json
  - ./credential_configurations/pid:sd_jwt_vc.json
  - ./credential_configurations/pid:sd_jwt_dc:arf_1_5.json
  - ./credential_configurations/pid:sd_jwt_vc:arf_1_5.json
  - ./credential_configurations/pid:mso_mdoc.json
  - ./credential_configurations/diploma.json
  - ./credential_configurations/ehic.json
  - ./credential_configurations/por:sd_jwt_vc.json
