name: Lint and formatting

on: [push]

jobs:
  test:
    strategy:
      matrix:
        pnpm-version: ['10.15.0']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup pnpm ${{ matrix.pnpm-version }}
      uses: pnpm/action-setup@v3
      with:
        version: ${{ matrix.pnpm-version }}
    - run: pnpm install --frozen-lockfile
    - run: pnpm run biome:ci
